#!/usr/bin/env python3
"""bin2c.py OUT.c NAME=FILE...: embed files as `const unsigned char NAME[]` + `const unsigned NAME_size`."""
import sys
with open(sys.argv[1], "w") as o:
    o.write("/* generated by tools/bin2c.py - do not edit */\n")
    for arg in sys.argv[2:]:
        name, path = arg.split("=", 1)
        b = open(path, "rb").read()
        o.write("const unsigned %s_size = %d;\nconst unsigned char %s[%d] = {" % (name, len(b), name, max(1, len(b))))
        o.write(",".join(str(x) for x in b) or "0")
        o.write("};\n")
